#<center/>TestCase#
###1.单元测试和测试用例###
Python标准库中的模块unittest提供了代码测试工具。单元测试用于核实函数的某个方面没有问题；测试用例是一组单元测试，这些单元测试一起核实函数在各种情形下的行为都符合要求。良好的测试用例考虑到了函数可能收到的各种输入，包含针对所有这些情形的测试。全覆盖式测试用例包含一整套单元测试，涵盖了各种可能的函数使用方式。对于大型项目，要实现全覆盖可能很难。通常，最初只要针对代码的重要行为编写测试即可，等项目被广泛使用时再考虑全覆盖。
要为函数编写测试用例，可先导入模块unittest以及要测试的函数，再创建一个继承unittest.TestCase的类，并编写一系列方法对函数行为的不同方面进行测试。

		#name_function.py
		def get_formatted_name(first, last):
			"""Generate a neatly formatted full name."""
			full_name = first + ' ' + last
			return full_name.title()
		def get_formatted_name2(first,last,middle=' '):
			"""Generate a neatly formatted full name."""
			full_name = first +' '+middle+' '+last
			return full_name.title()

		#TestCase.py
		import unittest
		from name_function import get_formatted_name
		from name_function import get_formatted_name2
		
		class NamesTestCase(unittest.TestCase):
			"""测试name_function.py"""
			def test_first_last_name(self):
				"""能够正确地处理像Janis Joplin这样的姓名？"""
				formatted_name = get_formatted_name("janis","joplin")
				self.assertEqual(formatted_name,'Janis Joplin')
			def test_first_last_middle_name(self):
				"""能够正确地处理像Wolfgang Amadeus Mozart这样的姓名吗？"""
				formatted_name = get_formatted_name2('wolfgang', 'mozart', 'amadeus')
				self.assertEqual(formatted_name, 'Wolfgang Amadeus Mozart')
		unittest.main()
		输出：
			..
			----------------------------------------------------------------------
			Ran 2 tests in 0.000s
			
			OK
			
			
			------------------
>①首先，我们导入了模块unittest和要测试的函数get_formatted_ name()。
>②创建了一个名为NamesTestCase的类，用于包含一系列针对get_formatted_name()的单元测试。可随便给这个类命名，但最好让它看起来与要测试的函数相关，并包含字样Test。这个类必须继承unittest.TestCase类，这样Python才知道如何运行你编写的测试。
>③运行test_name_function.py时，所有以test_打头的方法都将自动运行。
>④使用了unittest类最有用的功能之一：一个断言方法。断言方法用来核实得到的结果是否与期望的结果一致。
>⑤。方法名必须以test_打头，这样它才会在我们运行test_name_function.py时自动运行。这个方法名清楚地指出了它测试的是get_formatted_name()的哪个行为，这样，如果该测试未通过，我们就会马上知道受影响的是哪种类型的姓名。在TestCase类中使用很长的方法名是可以的；这些方法的名称必须是描述性的，这才能让你明白测试未通过时的输出；这些方法由Python自动调用，你根本不用编写调用它们的代码。

输出结果：
>第1行的句点表明有2个测试通过了。接下来的一行指出Python运行了2个测试，消耗的时间不到0.001秒。最后的OK表明该测试用例中的所有单元测试都通过了。

###2.未通过的测试###

		#name_function.py
		def get_formatted_name(first, last):
			"""Generate a neatly formatted full name."""
			full_name = first + ' ' + last
			return full_name.title()
		def get_formatted_name2(first,last,middle):
			"""Generate a neatly formatted full name."""
			full_name = first +' '+middle+' '+last
			return full_name.title()
		
		#TestCase.py
		import unittest
		from name_function import get_formatted_name
		from name_function import get_formatted_name2
		
		class NamesTestCase(unittest.TestCase):
			"""测试name_function.py"""
			def test_first_last_name2(self):
				"""能够正确地处理像Janis Joplin这样的姓名？"""
				formatted_name = get_formatted_name2("janis","joplin")
				self.assertEqual(formatted_name,'Janis Joplin')
		unittest.main()
		输出：
			E
			======================================================================
			ERROR: test_first_last_name (__main__.NamesTestCase)
			能够正确地处理像Janis Joplin这样的姓名？
			----------------------------------------------------------------------
			Traceback (most recent call last):
			  File "TestCase01.py", line 12, in test_first_last_name
			    formatted_name = get_formatted_name2("janis","joplin")
			TypeError: get_formatted_name2() takes exactly 3 arguments (2 given)
			
			----------------------------------------------------------------------
			Ran 1 test in 0.002s
			
			FAILED (errors=1)
			
			
			------------------
>其中包含的信息很多，因为测试未通过时，需要让你知道的事情可能有很多。第1行输出只有一个字母E，它指出测试用例中有一个单元测试导致了错误。接下来，我们看到NamesTestCase中的test_first_last_name()导致了错误。测试用例包含众多单元测试时，知道哪个测试未通过至关重要。在处，我们看到了一个标准的traceback，它指出函数调用get_formatted_name2('janis', 'joplin')有问题，因为它缺少一个必不可少的位置实参。我们还看到运行了一个单元测试。最后，还看到了一条消息，它指出整个测试用例都未通过，因为运行该测试用例时发生了一个错误。这条消息位于输出末尾，让你一眼就能看到——你可不希望为获悉有多少测试未通过而翻阅长长的输出。
>
>测试未通过时，不要修改测试，而应修复导致测试不能通过的代码：检查刚对函数所做的修改，找出导致函数行为不符合预期的修改。